import type { Metadata } from "next";

import { AuthProvider } from "../../interceptors/auth/authContext";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import ConditionalNavbar from "./components/ConditionalNavbar";

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-open-sans",
  display: "swap",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: "Swift Food - Bringing London's streetfood to your company",
  description:
    "We provide food delivery of the best street food in London to corporations",
  keywords: [
    "corporate",
    "food delivery",
    "UK",
    "street food",
    "streetfood",
    "delivery",
  ],
  authors: [{ name: "Swift Food Services ltd" }],

  icons: {
    icon: "/favicon.png",
    apple: "/favicon.png",
  },

  openGraph: {
    type: "website",
    locale: "en_GB",
    url: "https://swiftfood.uk",
    siteName: "Swift Food",
    title: "Swift Food - Bringing London's streetfood to you",
    description:
      "We provide event ordering and delivery of the best street food in London",
  },

  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },

  verification: {
    google: "bu1_vFJg_q2u8Syf9Cith5Q6G_Zld7hqwqLw8gDdtSM", // Add this from Google Search Console
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${openSans.className} ${openSans.variable}`}>
        <AuthProvider>
          <div className="min-h-screen flex flex-col">
            <ConditionalNavbar />
            <main className="flex-1">{children}</main>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
